In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("albenft/game-of-thrones-script-all-seasons")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.8), please consider upgrading to the latest version (0.3.11).
Downloading from https://www.kaggle.com/api/v1/datasets/download/albenft/game-of-thrones-script-all-seasons?dataset_version_number=1...

100%|████████████████████████████████████████| 691k/691k [00:00<00:00, 15.8MB/s]

Extracting files...
Path to dataset files: /Users/evelynchu/.cache/kagglehub/datasets/albenft/game-of-thrones-script-all-seasons/versions/1

In [2]:
pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /Users/evelynchu/Library/Python/3.12/lib/python/site-packages (from pandas) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import os

directory = "/Users/evelynchu/.cache/kagglehub/datasets/albenft/game-of-thrones-script-all-seasons/versions/1"
print("Files in directory:")
print(os.listdir(directory))

Files in directory:
['Game_of_Thrones_Script.csv']

In [5]:
# Read the csv file 
import pandas as pd
import os

directory = "/Users/evelynchu/.cache/kagglehub/datasets/albenft/game-of-thrones-script-all-seasons/versions/1"
Game_of_Thrones_text = os.path.join(directory, "Game_of_Thrones_Script.csv")

file = pd.read_csv(Game_of_Thrones_text)
print(file)

      Release Date    Season    Episode     Episode Title              Name  \
0       2011-04-17  Season 1  Episode 1  Winter is Coming      waymar royce
1       2011-04-17  Season 1  Episode 1  Winter is Coming              will
2       2011-04-17  Season 1  Episode 1  Winter is Coming      waymar royce
3       2011-04-17  Season 1  Episode 1  Winter is Coming              will
4       2011-04-17  Season 1  Episode 1  Winter is Coming             gared
...            ...       ...        ...               ...               ...
23906   2019-05-19  Season 8  Episode 6   The Iron Throne           brienne
23907   2019-05-19  Season 8  Episode 6   The Iron Throne             bronn
23908   2019-05-19  Season 8  Episode 6   The Iron Throne  tyrion lannister
23909   2019-05-19  Season 8  Episode 6   The Iron Throne               man
23910   2019-05-19  Season 8  Episode 6   The Iron Throne               all

                                                Sentence
0      What do you expect? They're savages. One lot s...
1      I've never seen wildlings do a thing like this...
2                                 How close did you get?
3                                Close as any man would.
4                       We should head back to the wall.
...                                                  ...
23906  I think we can all agree that ships take prece...
23907      I think that's a very presumptuous statement.
23908  I once brought a jackass and a honeycomb into ...
23909                            The Queen in the North!
23910  The Queen in the North! The Queen in the North...

[23911 rows x 6 columns]

## Main Title

## The Rains of Castamere

S2 E1 The North Remembers

Tyrion Lannister hums 'The Rains of Castamere' as he walks into the small council meeting.
After humming briefly, Tyrion sumply greets the council members and begins speaking.
[Background] Emphasizing the power of House Lannister and Tyrion's confidence.

S2 E9 Blackwater: reinforce the power and merciless dominance of House Lannister over those who defy them.

1. Bronn and the Lannister soldiers singing

In [85]:
# Select scripts
S2E9 = file[(file['Season'] == 'Season 2') & 
(file['Episode'] == 'Episode 9')].reset_index(drop=True)

# Target 'The Rains of Castamere'
keywords_rain1 = ['who are you', 'proud lord said']

for word in keywords_rain1:
    print(f"---{word}---")
    display(S2E9[S2E9['Sentence'].str.contains(word, case=False, na=False)])

---who are you---

,Release Date,Season,Episode,Episode Title,Name,Sentence
355,2012-05-27,Season 2,Episode 9,Blackwater,male singer,"And who are you,"" the proud lord said / ""That ..."

---proud lord said---

,Release Date,Season,Episode,Episode Title,Name,Sentence
355,2012-05-27,Season 2,Episode 9,Blackwater,male singer,"And who are you,"" the proud lord said / ""That ..."

2. End credits performanceed by the band The National

In [83]:
from IPython.display import display
display(S2E9)

,Release Date,Season,Episode,Episode Title,Name,Sentence
0,2012-05-27,Season 2,Episode 9,Blackwater,matthos,That's it. The tide's against us.
1,2012-05-27,Season 2,Episode 9,Blackwater,davos,"Aye, but we have the wind. She'll blow us stra..."
2,2012-05-27,Season 2,Episode 9,Blackwater,matthos,You're coming home.
3,2012-05-27,Season 2,Episode 9,Blackwater,davos,King's Landing hasn't been home for twenty yea...
4,2012-05-27,Season 2,Episode 9,Blackwater,matthos,This is the royal fleet. And you're not a smug...
...,...,...,...,...,...,...
351,2012-05-27,Season 2,Episode 9,Blackwater,stannis baratheon,"Stand and fight! Stand and fight, damn you!"
352,2012-05-27,Season 2,Episode 9,Blackwater,stannis baratheon,No!
353,2012-05-27,Season 2,Episode 9,Blackwater,cersei lannister,Father.
354,2012-05-27,Season 2,Episode 9,Blackwater,tywin lannister,The battle is over. We have won.
355,2012-05-27,Season 2,Episode 9,Blackwater,male singer,"And who are you,"" the proud lord said / ""That ..."

S3 E8：Second Sons

In [84]:
# Select scripts
S3E8 = file[(file['Season'] == 'Season 3') & 
(file['Episode'] == 'Episode 8')].reset_index(drop=True)

In [87]:
# Lock the starting of the song 'The Rains of Castamere'
keywords_rain2s = ['radiant', 'your grace']

for word in keywords_rain2s:
    print(f"---{word}---")
    display(S3E8[S3E8['Sentence'].str.contains(word, case=False, na=False)])

---radiant---

,Release Date,Season,Episode,Episode Title,Name,Sentence
136,2013-05-19,Season 3,Episode 8,Second Sons,margaery tyrell,"You look radiant, Your Grace."
137,2013-05-19,Season 3,Episode 8,Second Sons,cersei lannister,Radiant? Why radiant?

---your grace---

,Release Date,Season,Episode,Episode Title,Name,Sentence
22,2013-05-19,Season 3,Episode 8,Second Sons,barristan,"Two thousand, Your Grace. Armored and mounted."
29,2013-05-19,Season 3,Episode 8,Second Sons,barristan,"Your Grace, allow me to present the captains o..."
38,2013-05-19,Season 3,Episode 8,Second Sons,barristan,"Under two thousand, Your Grace."
63,2013-05-19,Season 3,Episode 8,Second Sons,barristan,"Gladly, Your Grace."
75,2013-05-19,Season 3,Episode 8,Second Sons,davos,Your Grace.
89,2013-05-19,Season 3,Episode 8,Second Sons,davos,"Forgive me, Your Grace, I'm not a learned man,..."
95,2013-05-19,Season 3,Episode 8,Second Sons,davos,"Your Grace, why did you come to see me today?"
99,2013-05-19,Season 3,Episode 8,Second Sons,davos,"Quite little, Your Grace. Verging on none. You..."
136,2013-05-19,Season 3,Episode 8,Second Sons,margaery tyrell,"You look radiant, Your Grace."
157,2013-05-19,Season 3,Episode 8,Second Sons,septon,"Your Grace, Your Grace, my lords, my ladies, w..."
185,2013-05-19,Season 3,Episode 8,Second Sons,gendry baratheon,"Please. Please, Your Grace. My lord!"
205,2013-05-19,Season 3,Episode 8,Second Sons,sansa stark,"Thank you, Your Grace."
207,2013-05-19,Season 3,Episode 8,Second Sons,sansa stark,"Yes, Your Grace."
216,2013-05-19,Season 3,Episode 8,Second Sons,tywin lannister,"I believe we can dispense with the bedding, Yo..."
217,2013-05-19,Season 3,Episode 8,Second Sons,tyrion lannister,"A bad joke, Your Grace. Made out of envy of yo..."
218,2013-05-19,Season 3,Episode 8,Second Sons,tywin lannister,"Your uncle is clearly quite drunk, Your Grace."
237,2013-05-19,Season 3,Episode 8,Second Sons,missandei,"Yes, Your Grace."
239,2013-05-19,Season 3,Episode 8,Second Sons,missandei,It only took Your Grace a year to learn Dothra...
248,2013-05-19,Season 3,Episode 8,Second Sons,missandei,"Your High Valyrian is very good, Your Grace. T..."

In [88]:
# Lock the end of the song 'The Rains of Castamere'
keywords_rain2e = ['gone', 'strangled', 'sleep']

for word in keywords_rain2e:
    print(f"---{word}---")
    display(S3E8[S3E8['Sentence'].str.contains(word, case=False, na=False)])

---gone---

,Release Date,Season,Episode,Episode Title,Name,Sentence
83,2013-05-19,Season 3,Episode 8,Second Sons,davos,I didn't know she'd been gone.
148,2013-05-19,Season 3,Episode 8,Second Sons,margaery tyrell,Gone.
149,2013-05-19,Season 3,Episode 8,Second Sons,cersei lannister,Gone. A gentle word. Why not say slaughtered? ...
153,2013-05-19,Season 3,Episode 8,Second Sons,joffrey lannister,Your father's gone. As the father of the realm...

---strangled---

,Release Date,Season,Episode,Episode Title,Name,Sentence
151,2013-05-19,Season 3,Episode 8,Second Sons,cersei lannister,"If you ever call me sister again, I'll have yo..."

---sleep---

,Release Date,Season,Episode,Episode Title,Name,Sentence
99,2013-05-19,Season 3,Episode 8,Second Sons,davos,"Quite little, Your Grace. Verging on none. You..."
151,2013-05-19,Season 3,Episode 8,Second Sons,cersei lannister,"If you ever call me sister again, I'll have yo..."

In [90]:
# Select scripts
S3E9 = file[(file['Season'] == 'Season 3') & 
(file['Episode'] == 'Episode 9')].reset_index(drop=True)

In [91]:
from IPython.display import display
display(S3E9)

,Release Date,Season,Episode,Episode Title,Name,Sentence
0,2013-06-02,Season 3,Episode 9,The Rains of Castamere,catelyn stark,Are you sure about this?
1,2013-06-02,Season 3,Episode 9,The Rains of Castamere,robb stark,No.
2,2013-06-02,Season 3,Episode 9,The Rains of Castamere,catelyn stark,It's dangerous.
3,2013-06-02,Season 3,Episode 9,The Rains of Castamere,robb stark,"If we take Tywin's castle from him, the lords ..."
4,2013-06-02,Season 3,Episode 9,The Rains of Castamere,catelyn stark,Why are you telling me?
...,...,...,...,...,...,...
291,2013-06-02,Season 3,Episode 9,The Rains of Castamere,walder,And why I would let him do that?
292,2013-06-02,Season 3,Episode 9,The Rains of Castamere,catelyn stark,"On my honor as a Tully, on my honor as a Stark..."
293,2013-06-02,Season 3,Episode 9,The Rains of Castamere,walder,I'll find another.
294,2013-06-02,Season 3,Episode 9,The Rains of Castamere,robb stark,Mother.
295,2013-06-02,Season 3,Episode 9,The Rains of Castamere,roose,The Lannisters send their regards.

In [25]:
# Lock the starting of the song 'The Rains of Castamere'
keywords_rainS = ['duties', 'wine', 'music', 'wedding gift']

for word in keywords_rainS:
    print(f"---{word}---")
    display(S3E9[S3E9['Sentence'].str.contains(word, case=False, na=False)])

---duties---

,Release Date,Season,Episode,Episode Title,Name,Sentence
280,2013-06-02,Season 3,Episode 9,The Rains of Castamere,walder,I feel I've been remiss in my duties.

---wine---

,Release Date,Season,Episode,Episode Title,Name,Sentence
33,2013-06-02,Season 3,Episode 9,The Rains of Castamere,walder,"Well, let's get ready. The wine will flow red ..."
281,2013-06-02,Season 3,Episode 9,The Rains of Castamere,walder,I've given you meat and wine and music but I h...

---music---

,Release Date,Season,Episode,Episode Title,Name,Sentence
33,2013-06-02,Season 3,Episode 9,The Rains of Castamere,walder,"Well, let's get ready. The wine will flow red ..."
281,2013-06-02,Season 3,Episode 9,The Rains of Castamere,walder,I've given you meat and wine and music but I h...

---wedding gift---

,Release Date,Season,Episode,Episode Title,Name,Sentence
281,2013-06-02,Season 3,Episode 9,The Rains of Castamere,walder,I've given you meat and wine and music but I h...

In [51]:
# Lock the end of the song 'The Rains of Castamere'
keywords_rainE = ['lord walder', 'first son', 'swear', 'vengeance']

for word in keywords_rainE:
    print(f"---{word}---")
    display(S3E9[S3E9['Sentence'].str.contains(word, case=False, na=False)])

---lord walder---

,Release Date,Season,Episode,Episode Title,Name,Sentence
243,2013-06-02,Season 3,Episode 9,The Rains of Castamere,roose,Aye. Lord Walder let me choose any of his gran...
257,2013-06-02,Season 3,Episode 9,The Rains of Castamere,robb stark,"If you think the time is right, Lord Walder, b..."
288,2013-06-02,Season 3,Episode 9,The Rains of Castamere,catelyn stark,"Lord Walder! Lord Walder, enough! Let it end! ..."

---first son---

,Release Date,Season,Episode,Episode Title,Name,Sentence
288,2013-06-02,Season 3,Episode 9,The Rains of Castamere,catelyn stark,"Lord Walder! Lord Walder, enough! Let it end! ..."

---swear---

,Release Date,Season,Episode,Episode Title,Name,Sentence
288,2013-06-02,Season 3,Episode 9,The Rains of Castamere,catelyn stark,"Lord Walder! Lord Walder, enough! Let it end! ..."

---vengeance---

,Release Date,Season,Episode,Episode Title,Name,Sentence
288,2013-06-02,Season 3,Episode 9,The Rains of Castamere,catelyn stark,"Lord Walder! Lord Walder, enough! Let it end! ..."

In [27]:
start_index = 281
end_index = 288
rains_segment = S3E9.loc[start_index:end_index]
display(rains_segment)

,Release Date,Season,Episode,Episode Title,Name,Sentence
281,2013-06-02,Season 3,Episode 9,The Rains of Castamere,walder,I've given you meat and wine and music but I h...
282,2013-06-02,Season 3,Episode 9,The Rains of Castamere,catelyn stark,Robb!
283,2013-06-02,Season 3,Episode 9,The Rains of Castamere,man,"You ready to head home to Winterfell, eh?"
284,2013-06-02,Season 3,Episode 9,The Rains of Castamere,man,"Feast over yet, is it?"
285,2013-06-02,Season 3,Episode 9,The Rains of Castamere,frey man,"Aye, it's over!"
286,2013-06-02,Season 3,Episode 9,The Rains of Castamere,sandor clegane,It's too late.
287,2013-06-02,Season 3,Episode 9,The Rains of Castamere,walder,"The King in the North arises, heh heh."
288,2013-06-02,Season 3,Episode 9,The Rains of Castamere,catelyn stark,"Lord Walder! Lord Walder, enough! Let it end! ..."

In [92]:
rains_segment.to_csv("S3E9_rains.csv", index=False)

S4E2：The Lion and the Rose

In [64]:
# Select scripts
S4E2 = file[(file['Season'] == 'Season 4') & 
(file['Episode'] == 'Episode 2')].reset_index(drop=True)

from IPython.display import display
display(S4E2)

,Release Date,Season,Episode,Episode Title,Name,Sentence
0,2014-04-13,Season 4,Episode 2,The Lion and the Rose,ramsay bolton,Tansy! Tansy! Tansy!
1,2014-04-13,Season 4,Episode 2,The Lion and the Rose,ramsay bolton,Tansy! Tansy!
2,2014-04-13,Season 4,Episode 2,The Lion and the Rose,ramsay bolton,There you are.
3,2014-04-13,Season 4,Episode 2,The Lion and the Rose,myranda,"I can't see her, Ramsay."
4,2014-04-13,Season 4,Episode 2,The Lion and the Rose,ramsay bolton,Tansy!
...,...,...,...,...,...,...
390,2014-04-13,Season 4,Episode 2,The Lion and the Rose,cersei lannister,Don't touch him!
391,2014-04-13,Season 4,Episode 2,The Lion and the Rose,cersei lannister,"Joffrey. Please, Joffrey. Joffrey, what is it?..."
392,2014-04-13,Season 4,Episode 2,The Lion and the Rose,cersei lannister,My son.
393,2014-04-13,Season 4,Episode 2,The Lion and the Rose,man,He's gone. Our king is gone.
394,2014-04-13,Season 4,Episode 2,The Lion and the Rose,cersei lannister,"He did this. He poisoned my son, your king. Ta..."

In [70]:
# Lock the end of the song 'The Rains of Castamere'
keywords_rainS = ['Prince Oberyn', 'Ellaria']

for word in keywords_rainS:
    print(f"---{word}---")
    display(S4E2[S4E2['Sentence'].str.contains(word, case=False, na=False)])

---Prince Oberyn---

,Release Date,Season,Episode,Episode Title,Name,Sentence
311,2014-04-13,Season 4,Episode 2,The Lion and the Rose,tywin lannister,Prince Oberyn.
320,2014-04-13,Season 4,Episode 2,The Lion and the Rose,cersei lannister,"I suppose you'll never know, Prince Oberyn. It..."

---Ellaria---

,Release Date,Season,Episode,Episode Title,Name,Sentence
312,2014-04-13,Season 4,Episode 2,The Lion and the Rose,oberyn martell,I don't believe you have met Ellaria. This is ...

In [78]:
# Lock the end of the song 'The Rains of Castamere'
keywords_rainE = ['royal wedding']

for word in keywords_rainE:
    print(f"---{word}---")
    display(S4E2[S4E2['Sentence'].str.contains(word, case=False, na=False)])

---royal wedding---

,Release Date,Season,Episode,Episode Title,Name,Sentence
325,2014-04-13,Season 4,Episode 2,The Lion and the Rose,joffrey lannister,"Everyone, silence! Clear the floor. There's be..."

## Light of the Seven

Season 6 Episode 10 The Wings of Winter
This is the first appearance of Light of the Seven, playede during the pivotal sequence in which Cersei Lannister orchestrates and executes the destruction of the Great Spet of Baelor. 
Piano + 10 mins

Season 8 Episode 5 The Bells
In this episode, a variation of Light of the Seven is used as Daenerys Targaryen begins her assault on King's Landing, foreshadowing Cersei's downfall.
It is primarily used to underscore Cersei Lannister's sense of despair as she watches King's Landing being destroyed by Daenerys Targaryen from within the Red Keep.

In [31]:
# Select full scripts
S6E10 = file[(file['Season'] == 'Season 6') & 
(file['Episode'] == 'Episode 10')].reset_index(drop=True)

In [100]:
# Lock the start of the song 'Light of the Seven'
keywords_light1s = ["sins", "trial"]

for word in keywords_light1s:
    print(f"---{word}---")
    display(S6E10[S6E10['Sentence'].str.contains(word, case=False, na=False)])

---sins---

,Release Date,Season,Episode,Episode Title,Name,Sentence
10,2016-06-26,Season 6,Episode 10,The Winds of Winter,loras,I take full responsibility for my many sins an...

---trial---

,Release Date,Season,Episode,Episode Title,Name,Sentence
0,2016-06-26,Season 6,Episode 10,The Winds of Winter,attendant,Your Grace. The trial will be getting underway...
4,2016-06-26,Season 6,Episode 10,The Winds of Winter,sparrow,Ser Loras Tyrell. Are you prepared to stand tr...
5,2016-06-26,Season 6,Episode 10,The Winds of Winter,loras,There'll be no need for a trial. I confess bef...
20,2016-06-26,Season 6,Episode 10,The Winds of Winter,tommen lannister,"I have to go, I'm-- I'm late for the trial."
22,2016-06-26,Season 6,Episode 10,The Winds of Winter,sparrow,I've kept my word. Once the queen mother's tri...
25,2016-06-26,Season 6,Episode 10,The Winds of Winter,sparrow,It appears the queen mother doesn't wish to at...
36,2016-06-26,Season 6,Episode 10,The Winds of Winter,sparrow,"You have nothing to fear, Your Grace. The tria..."
39,2016-06-26,Season 6,Episode 10,The Winds of Winter,margaery tyrell,Forget about the bloody gods and listen to wha...

In [95]:
# Lock the end of the song 'Light of the Seven'
keywords_light1e = ['confess']

for word in keywords_light1e:
    print(f"---{word}---")
    display(S6E10[S6E10['Sentence'].str.contains(word, case=False, na=False)])

---confess---

,Release Date,Season,Episode,Episode Title,Name,Sentence
5,2016-06-26,Season 6,Episode 10,The Winds of Winter,loras,There'll be no need for a trial. I confess bef...
6,2016-06-26,Season 6,Episode 10,The Winds of Winter,sparrow,To which crimes will you be confessing?
44,2016-06-26,Season 6,Episode 10,The Winds of Winter,cersei lannister,Confess. Confess.
46,2016-06-26,Season 6,Episode 10,The Winds of Winter,cersei lannister,Confess.
47,2016-06-26,Season 6,Episode 10,The Winds of Winter,cersei lannister,"Confess. It felt good. Beating me, starving me..."

## Jenny of Oldstones

In [38]:
# Select full scripts
S8E2 = file[(file['Season'] == 'Season 8') & 
(file['Episode'] == 'Episode 2')].reset_index(drop=True)

In [39]:
from IPython.display import display
display(S8E2)

,Release Date,Season,Episode,Episode Title,Name,Sentence
0,2019-04-21,Season 8,Episode 2,A Knight of the Seven Kingdoms,daenerys targaryen,"When I was a child, my brother would tell me a..."
1,2019-04-21,Season 8,Episode 2,A Knight of the Seven Kingdoms,daenerys targaryen,Who stabbed him in the back and cut his throat...
2,2019-04-21,Season 8,Episode 2,A Knight of the Seven Kingdoms,daenerys targaryen,He told me other stories as well. About all th...
3,2019-04-21,Season 8,Episode 2,A Knight of the Seven Kingdoms,daenerys targaryen,Your sister pledged to send her army north.
4,2019-04-21,Season 8,Episode 2,A Knight of the Seven Kingdoms,jaime lannister,She did.
...,...,...,...,...,...,...
400,2019-04-21,Season 8,Episode 2,A Knight of the Seven Kingdoms,jon snow,And Samwell confirmed it. He read about their ...
401,2019-04-21,Season 8,Episode 2,A Knight of the Seven Kingdoms,daenerys targaryen,A secret no one in the world knew except your ...
402,2019-04-21,Season 8,Episode 2,A Knight of the Seven Kingdoms,jon snow,"It's true, Dany. I know it is."
403,2019-04-21,Season 8,Episode 2,A Knight of the Seven Kingdoms,daenerys targaryen,"If it were true, it would make you the last ma..."
404,2019-04-21,Season 8,Episode 2,A Knight of the Seven Kingdoms,man,Form up! Get yourselves back!

In [42]:
# Lock the starting of the song 'Light of the Seven'
keywords_jennyS = ['podrick', 'jenny']

for word in keywords_jennyS:
    print(f"---{word}---")
    display(S8E2[S8E2['Sentence'].str.contains(word, case=False, na=False)])

---podrick---

Empty DataFrame
Columns: [Release Date, Season, Episode, Episode Title, Name, Sentence]
Index: []

---jenny---

,Release Date,Season,Episode,Episode Title,Name,Sentence
383,2019-04-21,Season 8,Episode 2,A Knight of the Seven Kingdoms,podrick,"High in the halls of the kings who are gone, J..."

In [44]:
# Lock the end of the song 'Light of the Seven'
keywords_jennyE = ['campfire', 'silence']

for word in keywords_jennyE:
    print(f"---{word}---")
    display(S8E2[S8E2['Sentence'].str.contains(word, case=False, na=False)])

---campfire---

Empty DataFrame
Columns: [Release Date, Season, Episode, Episode Title, Name, Sentence]
Index: []

---silence---

Empty DataFrame
Columns: [Release Date, Season, Episode, Episode Title, Name, Sentence]
Index: []

## The Night King

In [45]:
# Select full scripts
S8E3 = file[(file['Season'] == 'Season 8') & 
(file['Episode'] == 'Episode 3')].reset_index(drop=True)

In [46]:
from IPython.display import display
display(S8E3)

,Release Date,Season,Episode,Episode Title,Name,Sentence
0,2019-04-28,Season 8,Episode 3,The Long Night,northman,Oi!
1,2019-04-28,Season 8,Episode 3,The Long Night,northman,Mind out.
2,2019-04-28,Season 8,Episode 3,The Long Night,northman,MOVE!
3,2019-04-28,Season 8,Episode 3,The Long Night,northman,"Look, on the west wall!"
4,2019-04-28,Season 8,Episode 3,The Long Night,soldier,Get down to the crypt!
...,...,...,...,...,...,...
150,2019-04-28,Season 8,Episode 3,The Long Night,daenerys targaryen,Jorah!
151,2019-04-28,Season 8,Episode 3,The Long Night,bran stark,Theon.
152,2019-04-28,Season 8,Episode 3,The Long Night,bran stark,You're a good man.
153,2019-04-28,Season 8,Episode 3,The Long Night,bran stark,Thank you.
154,2019-04-28,Season 8,Episode 3,The Long Night,jorah mormont,I'm hurt.

In [47]:
# Lock the starting of the song 'Light of the Seven'
keywords_nightS = ['theon', 'godswood']

for word in keywords_nightS:
    print(f"---{word}---")
    display(S8E3[S8E3['Sentence'].str.contains(word, case=False, na=False)])

---theon---

    Release Date    Season    Episode   Episode Title        Name Sentence
151   2019-04-28  Season 8  Episode 3  The Long Night  bran stark   Theon.

---godswood---

Empty DataFrame
Columns: [Release Date, Season, Episode, Episode Title, Name, Sentence]
Index: []

In [48]:
# Lock the end of the song 'Light of the Seven'
keywords_nightE = ['arya', 'kill', 'shatter']

for word in keywords_nightE:
    print(f"---{word}---")
    display(S8E3[S8E3['Sentence'].str.contains(word, case=False, na=False)])

---arya---

Empty DataFrame
Columns: [Release Date, Season, Episode, Episode Title, Name, Sentence]
Index: []

---kill---

Empty DataFrame
Columns: [Release Date, Season, Episode, Episode Title, Name, Sentence]
Index: []

---shatter---

Empty DataFrame
Columns: [Release Date, Season, Episode, Episode Title, Name, Sentence]
Index: []